[package]
name = "my-addon-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
event-manager = "0.4.0"
fusevm = "0.26.8"
kvm-bindings = "0.14.0"
kvm-ioctls = "0.24.0"
linux-loader = "0.13.0"
napi = { version = "3", features = ["async", "tokio_rt"] }
napi-derive = "3"
runtime-rs = { git = "https://github.com/kata-containers/kata-containers.git", version = "0.1.0" }
seccompiler = "0.5.0"
tokio = { version = "1", features = ["full"] }
vfio-bindings = "0.6.2"
vfio-ioctls = "0.6.0"
virtio-bindings = "0.2.0"
virtio-queue = "0.17.0"
vm-fdt = "0.3.0"
vm-memory = "=0.17.1"
vm-superio = "0.8.0"
vmm-sys-util = "0.15.0"

[build-dependencies]
napi-build = "2"
