/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class Cipher {
  constructor(algorithm: string, key: Buffer, iv: Buffer);
  setAad(buffer: Buffer): void;
  update(data: Buffer | string): Buffer;
  final(): Buffer;
  getAuthTag(): Buffer;
}
export { Cipher as Cipheriv };

export declare class CryptoKeyPair {
  constructor(publicKey: Buffer, privateKey: Buffer);
  get publicKey(): KeyObject;
  get privateKey(): KeyObject;
}

export declare class Decipher {
  constructor(algorithm: string, key: Buffer, iv: Buffer);
  setAad(buffer: Buffer): void;
  setAuthTag(buffer: Buffer): void;
  update(data: Buffer | string): Buffer;
  final(): Buffer;
}
export { Decipher as Decipheriv };

export declare class Ecdh {
  constructor(curveName: string);
  generateKeys(): Buffer;
  computeSecret(otherPublicKey: Buffer): Buffer;
  getPublicKey(): Buffer;
  getPrivateKey(): Buffer;
  setPrivateKey(privateKey: Buffer): void;
  setPublicKey(publicKey: Buffer): void;
}
export type ECDH = Ecdh;
export type DiffieHellman = Ecdh;
export type DiffieHellmanGroup = Ecdh;

export declare class Hash {
  constructor(algorithm: string);
  update(data: Buffer | string): void;
  digest(encoding?: string | undefined | null): Buffer | string;
}

export declare class Hmac {
  constructor(algorithm: string, key: Buffer | string);
  update(data: Buffer | string): void;
  digest(encoding?: string | undefined | null): Buffer | string;
}

export declare class KeyObject {
  keyType: string;
  asymmetricKeyType?: string;
  rawData: Array<number>;
  constructor(keyType: string, rawData: Buffer, asymmetricKeyType?: string | undefined | null);
  get type(): string;
  get asymmetricKeyType(): string | null;
  export(format?: string | undefined | null): Buffer | string;
  equals(other: KeyObject): boolean;
}

export declare class Sign {
  constructor(algorithm: string);
  update(data: Buffer | string): void;
  sign(keyPem: string): Buffer;
}

export declare class Tls {
  constructor(provider?: string | undefined | null);
  get provider(): string;
  get ciphersuites(): Array<string>;
  connect(host: string, port: number): boolean;
  isConnected(): boolean;
}
export type TLS = Tls;

export declare class Verify {
  constructor(algorithm: string);
  update(data: Buffer | string): void;
  verify(keyPem: string, signature: Buffer): boolean;
}

export declare class X509Certificate {
  constructor(input: Buffer | string);
  get raw(): Buffer;
  get subject(): string;
  get issuer(): string;
  get validFrom(): string;
  get validTo(): string;
  get serialNumber(): string;
  get fingerprint256(): string;
  get fingerprint512(): string;
  checkEmail(email: string): boolean;
  checkHost(name: string): boolean;
  checkIp(ip: string): boolean;
  toString(): string;
}

export declare class Certificate {
  static exportChallenge(spkac: Buffer): Buffer;
  static exportPublicKey(spkac: Buffer): Buffer;
  static verifySpkac(spkac: Buffer): boolean;
}

export declare function argon2(
  algorithm: string,
  parameters: Argon2Parameters,
  callback?: (err: Error | null, derivedKey?: Buffer) => void,
): Buffer | void;

export interface Argon2Parameters {
  message: Buffer | string;
  nonce: Buffer | string;
  parallelism: number;
  tagLength: number;
  memory: number;
  passes: number;
  secret?: Buffer | string;
  associatedData?: Buffer | string;
}

export declare function argon2Sync(algorithm: string, parameters: Argon2Parameters): Buffer;

export declare function checkPrimeSync(candidate: Buffer): boolean;
export declare function checkPrime(
  candidate: Buffer,
  callback?: (err: Error | null, isPrime?: boolean) => void,
): boolean | void;

export declare function generatePrimeSync(size: number): Buffer;
export declare function generatePrime(
  size: number,
  callback?: (err: Error | null, prime?: Buffer) => void,
): Buffer | void;

export declare function timingSafeEqual(a: Buffer, b: Buffer): boolean;

export interface GenerateKeyOptions {
  length: number;
}
export declare function generateKeySync(type: string, options: GenerateKeyOptions): KeyObject;
export declare function generateKey(
  type: string,
  options: GenerateKeyOptions,
  callback?: (err: Error | null, key?: KeyObject) => void,
): KeyObject | void;

export declare function scryptSync(
  password: Buffer | string,
  salt: Buffer | string,
  keylen: number,
  options?: ScryptOptions | undefined | null,
): Buffer;

export declare function scrypt(
  password: Buffer | string,
  salt: Buffer | string,
  keylen: number,
  options?: ScryptOptions | undefined | null,
  callback?: (err: Error | null, key?: Buffer) => void,
): Buffer | void;

export interface ScryptOptions {
  cost?: number;
  blockSize?: number;
  parallelization?: number;
  maxmem?: number;
}

export declare function createCipheriv(algorithm: string, key: Buffer, iv: Buffer): Cipher;

export declare function createDecipheriv(algorithm: string, key: Buffer, iv: Buffer): Decipher;

export declare function createDiffieHellman(primeOrLength: number | Buffer): Ecdh;

export declare function createDiffieHellmanGroup(groupName: string): Ecdh;

export declare const getDiffieHellman: typeof createDiffieHellmanGroup;

export declare function createECDH(curveName: string): Ecdh;

export declare function createHash(algorithm: string): Hash;

export declare function createHmac(algorithm: string, key: Buffer | string): Hmac;

export declare function createMac(algorithm: string, key: Buffer | string): Hmac;

export declare function createPrivateKey(key: Buffer | string): KeyObject;

export declare function createPublicKey(key: Buffer | string): KeyObject;

export declare function createSecretKey(key: Buffer | string): KeyObject;

export declare function createSign(algorithm: string): Sign;

export declare function createVerify(algorithm: string): Verify;

export declare function decapsulate(key: Buffer, ciphertext: Buffer): Buffer;

export declare function diffieHellman(privateKey: Buffer, publicKey: Buffer): Buffer;

export declare function encapsulate(key: Buffer): EncapsulateResult;

export interface EncapsulateResult {
  sharedKey: Buffer;
  ciphertext: Buffer;
}

export declare function exportPkcs8(keyBytes: Buffer): string;

export declare function parsePKCS12(bundle: Buffer): Pkcs12Result;
export interface Pkcs12Result {
  privateKey?: string;
  certificate?: string;
}

export declare function generateKeyPair(
  type: string,
  options?: RsaGenerateOptions | undefined | null,
): KeyPairResult;

export declare function generateKeyPairSync(
  type: string,
  options?: RsaGenerateOptions | undefined | null,
): KeyPairResult;

export declare function getCiphers(): Array<string>;
export interface CipherInfo {
  name: string;
  blockSize?: number;
  ivLength?: number;
  keyLength: number;
  mode: string;
}
export declare function getCipherInfo(name: string): CipherInfo;
export declare function getCurves(): Array<string>;
export declare function getHashes(): Array<string>;
export declare function getMacs(): Array<string>;
export declare function getFips(): number;
export declare function setFips(val: boolean): void;
export declare function setEngine(engine: string, flags?: number): void;
export interface SecureHeapInfo {
  total: number;
  min: number;
  used: number;
  utilization: number;
}
export declare function secureHeapUsed(): SecureHeapInfo;

export declare function hash(
  algorithm: string,
  data: Buffer | string,
  encoding?: string | undefined | null,
): Buffer | string;

export declare function hkdf(
  digest: string,
  ikm: Buffer | string,
  salt: Buffer | string,
  info: Buffer | string,
  keylen: number,
): Buffer;

export declare function hkdfSync(
  digest: string,
  ikm: Buffer | string,
  salt: Buffer | string,
  info: Buffer | string,
  keylen: number,
): Buffer;

export interface KeyPairResult {
  publicKey: string;
  privateKey: string;
}

export declare function parsePkcs8(input: Buffer | string): Pkcs8Info;

export declare function pbkdf2(
  password: Buffer | string,
  salt: Buffer | string,
  iterations: number,
  keylen: number,
  digest: string,
): Buffer;

export declare function pbkdf2Sync(
  password: Buffer | string,
  salt: Buffer | string,
  iterations: number,
  keylen: number,
  digest: string,
): Buffer;

export interface Pkcs8Info {
  algorithmOid: string;
  isEncrypted: boolean;
}

export declare function privateDecrypt(keyPem: string, buffer: Buffer): Buffer;
export declare function privateEncrypt(keyPem: string, buffer: Buffer): Buffer;
export declare function publicDecrypt(keyPem: string, buffer: Buffer): Buffer;
export declare function publicEncrypt(keyPem: string, buffer: Buffer): Buffer;

export declare function randomBytes(size: number): Buffer;
export declare const prng: typeof randomBytes;
export declare const pseudoRandomBytes: typeof randomBytes;
export declare const rng: typeof randomBytes;

export declare function randomFill(
  buffer: Buffer,
  offset?: number | undefined | null,
  size?: number | undefined | null,
): Buffer;

export declare function randomFillSync(
  buffer: Buffer,
  offset?: number | undefined | null,
  size?: number | undefined | null,
): Buffer;

export declare function randomInt(minOrMax: number, max?: number | undefined | null): number;

export declare function randomUUID(): string;
export declare function randomUUIDv7(): string;

export interface RsaGenerateOptions {
  modulusLength?: number;
  publicExponent?: number;
}

export declare function sign(algorithm: string, data: Buffer | string, keyPem: string): Buffer;

export declare function verify(
  algorithm: string,
  data: Buffer | string,
  keyPem: string,
  signature: Buffer,
): boolean;

export declare const constants: Record<string, number>;
export declare function getRandomValues<T extends ArrayBufferView>(array: T): T;
export declare const webcrypto: {
  getRandomValues: typeof getRandomValues;
  subtle: Record<string, any>;
};
export declare const subtle: Record<string, any>;
export declare const fips: number;
