/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Ksuid {
  /** Create a new Ksuid with an optional timestamp (in seconds since UNIX epoch) and optional 16-byte payload. */
  constructor(timestamp?: number | undefined | null, payload?: Uint8Array | undefined | null)
  /** Timestamp is now, payload is randomly generated or provided. */
  static now(payload?: Uint8Array | undefined | null): Ksuid
  /** Create a Ksuid from base62 string representation. */
  static fromBase62(base62: string): Ksuid
  /** Alias for from_base62 / FromStr logic. */
  static fromStr(s: string): Ksuid
  /** Create a Ksuid from 20 raw bytes. */
  static fromBytes(bytes: Uint8Array): Ksuid
  /** Explicitly create Ksuid from timestamp seconds and optional payload. */
  static fromSeconds(seconds?: number | undefined | null, payload?: Uint8Array | undefined | null): Ksuid
  /** Create a Ksuid from Crockford Base32 encoded string with optional custom alphabet. */
  static fromCrockfordBase32(str: string, alphabet?: string | undefined | null): Ksuid
  /** Base62 string representation. */
  toString(): string
  /** Base62 string representation (explicit alias). */
  toBase62(): string
  /** Encode Ksuid to Crockford Base32 string with optional custom 32-character alphabet. */
  toCrockfordBase32(alphabet?: string | undefined | null): string
  /** 20-byte slice representing the Ksuid. */
  bytes(): Uint8Array
  /** 16-byte payload portion of the Ksuid. */
  payloadBytes(): Uint8Array
  /** Timestamp in seconds since UNIX epoch. */
  timestampSeconds(): number
  /** Compare two Ksuids: returns -1 if self < other, 0 if equal, 1 if self > other. */
  compareTo(other: Ksuid): number
  /** Check equality with another Ksuid instance. */
  equals(other: Ksuid): boolean
}

/** Utility function to shuffle an alphabet deterministically with an optional seed (or randomly if no seed is provided). */
export declare function shuffleAlphabet(alphabet: string, seed?: string | undefined | null): string
