/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

import { createRequire } from "module";
const require = createRequire(import.meta.url);

const { readFileSync } = require("fs");
let nativeBinding = null;
let __napiLoadedBindingTarget = "native";
const loadErrors = [];

const isMusl = () => {
  let musl = false;
  if (process.platform === "linux") {
    musl = isMuslFromFilesystem();
    if (musl === null) {
      musl = isMuslFromReport();
    }
    if (musl === null) {
      musl = isMuslFromChildProcess();
    }
  }
  return musl;
};

const isFileMusl = (f) => f.includes("libc.musl-") || f.includes("ld-musl-");

const isMuslFromFilesystem = () => {
  try {
    return readFileSync("/usr/bin/ldd", "utf-8").includes("musl");
  } catch {
    return null;
  }
};

const isMuslFromReport = () => {
  let report = null;
  if (process.report && typeof process.report.getReport === "function") {
    process.report.excludeNetwork = true;
    report = process.report.getReport();
  }
  if (!report) {
    return null;
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false;
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true;
    }
  }
  return false;
};

const isMuslFromChildProcess = () => {
  try {
    return require("child_process")
      .execSync("ldd --version", { encoding: "utf8" })
      .includes("musl");
  } catch (e) {
    return false;
  }
};

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err);
    }
  } else if (process.platform === "linux") {
    if (process.arch === "x64") {
      try {
        return require("./my-addon.linux-x64-gnu.node");
      } catch (e) {
        loadErrors.push(e);
      }
    }
  }
  try {
    return require("./my-addon.linux-x64-gnu.node");
  } catch (e) {
    loadErrors.push(e);
  }
}

nativeBinding = requireNative();

if (!nativeBinding) {
  throw new Error(`Failed to load native binding`);
}

export const {
  Container,
  GetOrCreateResult,
  ImageHandle,
  VolumeHandle,
  ContainerCompose,
  ContainerBuild,
  ContainerRegistry,
} = nativeBinding;
export const __napiBindingTarget = __napiLoadedBindingTarget;
