/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Ksuid {
  constructor(options?: KsuidOptions | undefined | null)
  static now(options?: KsuidOptions | undefined | null): Ksuid
  static parse(input: string, options?: KsuidOptions | undefined | null): Ksuid
  toString(): string
  toBase62(): string
  toCrockford(customAlphabet?: string | undefined | null): string
  bytes(): Uint8Array
  timestampSeconds(): number
  timestampMillis(): number
}

export declare function crockfordDecode(input: string, customAlphabet?: string | undefined | null): number

export declare function crockfordEncode(n: number, customAlphabet?: string | undefined | null): string

export declare function decodeBytesCustom(input: string, alphabet: string): Uint8Array

export declare function encodeBytesCustom(bytes: Uint8Array, alphabet: string): string

export declare function ksuidFromBase62(base62: string): string

export declare function ksuidFromCrockford(crockford: string, customAlphabet?: string | undefined | null): string

export interface KsuidOptions {
  enc?: string
  encoding?: string
  alphabet?: string
  timestampSize?: string
  bytes?: Uint8Array
  string?: string
  timestamp?: number
}

export declare function ksuidTimestampSeconds(base62: string): number

export declare function ksuidToBytes(base62: string): Uint8Array

export declare function ksuidToCrockford(base62: string, customAlphabet?: string | undefined | null): string

export declare function newKsuid(): string
