/* auto-generated by NAPI-RS */
/* eslint-disable */

/** The WASI flavor this loader instantiates. */
export declare const __napiBindingTarget: 'wasm32-wasi'

export declare function add(left: number, right: number): number
