/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Ksuid {
  get PAYLOAD_BYTES(): number
  get BYTES(): number
  static now(payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): Ksuid
  static new(timestamp?: number | undefined | null, payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): Ksuid
  static fromBase62(base62: string, options?: KsuidOptions | undefined | null): Ksuid
  static from_base62(base62: string, options?: KsuidOptions | undefined | null): Ksuid
  static fromBase32(base32: string, options?: KsuidOptions | undefined | null): Ksuid
  static from_base32(base32: string, options?: KsuidOptions | undefined | null): Ksuid
  static fromStr(s: string, options?: KsuidOptions | undefined | null): Ksuid
  static from_str(s: string, options?: KsuidOptions | undefined | null): Ksuid
  static fromBytes(bytes: Uint8Array, options?: KsuidOptions | undefined | null): Ksuid
  static from_bytes(bytes: Uint8Array, options?: KsuidOptions | undefined | null): Ksuid
  static fromSeconds(seconds?: number | undefined | null, payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): Ksuid
  static from_seconds(seconds?: number | undefined | null, payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): Ksuid
  toBase62(): string
  to_base62(): string
  toBase32(): string
  to_base32(): string
  toString(): string
  to_string(): string
  bytes(): Buffer
  payload(): Buffer
  timestampSeconds(): number
  timestamp_seconds(): number
  timestamp(): number
  compare(other: Ksuid): number
  equals(other: Ksuid): boolean
  gt(other: Ksuid): boolean
  gte(other: Ksuid): boolean
  lt(other: Ksuid): boolean
  lte(other: Ksuid): boolean
}

export declare class KsuidMs {
  get PAYLOAD_BYTES(): number
  get BYTES(): number
  static now(payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): KsuidMs
  static new(timestamp?: number | undefined | null, payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): KsuidMs
  static fromBase62(base62: string, options?: KsuidOptions | undefined | null): KsuidMs
  static from_base62(base62: string, options?: KsuidOptions | undefined | null): KsuidMs
  static fromBase32(base32: string, options?: KsuidOptions | undefined | null): KsuidMs
  static from_base32(base32: string, options?: KsuidOptions | undefined | null): KsuidMs
  static fromStr(s: string, options?: KsuidOptions | undefined | null): KsuidMs
  static from_str(s: string, options?: KsuidOptions | undefined | null): KsuidMs
  static fromBytes(bytes: Uint8Array, options?: KsuidOptions | undefined | null): KsuidMs
  static from_bytes(bytes: Uint8Array, options?: KsuidOptions | undefined | null): KsuidMs
  static fromMillis(millis?: number | undefined | null, payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): KsuidMs
  static from_millis(millis?: number | undefined | null, payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): KsuidMs
  static fromSeconds(seconds?: number | undefined | null, payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): KsuidMs
  static from_seconds(seconds?: number | undefined | null, payload?: Uint8Array | undefined | null, options?: KsuidOptions | undefined | null): KsuidMs
  toBase62(): string
  to_base62(): string
  toBase32(): string
  to_base32(): string
  toString(): string
  to_string(): string
  bytes(): Buffer
  payload(): Buffer
  timestampSeconds(): number
  timestamp_seconds(): number
  timestampMillis(): number
  timestamp_millis(): number
  timestamp(): number
  compare(other: KsuidMs): number
  equals(other: KsuidMs): boolean
  gt(other: KsuidMs): boolean
  gte(other: KsuidMs): boolean
  lt(other: KsuidMs): boolean
  lte(other: KsuidMs): boolean
}

export declare function decodeCrockford(input: string): number

export declare function encodeCrockford(value: number): string

export interface KsuidOptions {
  enc?: string
  alphabet?: string
  timestampSize?: string
}
