/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: "native" | "wasm32-wasi" | "wasm32-wasip1";

/**
 * ContainerLite runtime instance.
 *
 * The main entry point for creating and managing containers. Each runtime
 * instance manages a separate data directory with its own containers, images,
 * and configuration.
 */
export declare class JsContainer {
  /** Create a new runtime with custom options. */
  constructor(options: JsOptions);
  /** Get the default runtime instance. */
  static withDefaultConfig(): JsContainer;
  /** Initialize the default runtime with custom options. */
  static initDefault(options: JsOptions): void;
  /**
   * Takes the `ContainerRestOptions` class; the positional->bag
   * adaptation lives in the binding (`JsContainerRestOptions::into_core`).
   */
  static rest(options: JsContainerRestOptions): JsContainer;
  /** Import a container from a `.container` archive. */
  importContainer(
    archivePath: string,
    name?: string | undefined | null,
  ): Promise<JsContainerHandle>;
  /** Create a new container. */
  create(options: JsContainerOptions, name?: string | undefined | null): Promise<JsContainerHandle>;
  /** Get an existing container by name, or create a new one if it doesn't exist. */
  getOrCreate(
    options: JsContainerOptions,
    name?: string | undefined | null,
  ): Promise<JsGetOrCreateResult>;
  /** List all containers managed by this runtime. */
  listInfo(): Promise<Array<JsContainerInfo>>;
  /** Get information about a specific container by ID or name. */
  getInfo(idOrName: string): Promise<JsContainerInfo | null>;
  /** Get a container handle by ID or name (for reattach or restart). */
  get(idOrName: string): Promise<JsContainerHandle | null>;
  /** Get runtime metrics. */
  metrics(): Promise<JsRuntimeMetrics>;
  /** Get the runtime image handle. */
  get images(): JsImageHandle;
  /** Get the runtime volume handle. */
  get volumes(): JsVolumeHandle;
  /** Remove a container by ID or name. */
  remove(idOrName: string, force?: boolean | undefined | null): Promise<void>;
  /** Close the runtime (no-op, provided for API compatibility). */
  close(): void;
  /** Gracefully shutdown all containers in this runtime. */
  shutdown(timeout?: number | undefined | null): Promise<void>;
}

export declare class JsContainerHandle {
  exec(command: string, args?: Array<string> | undefined | null): Promise<string>;
  stop(): Promise<void>;
  start(): Promise<void>;
}

export declare class JsContainerRestOptions {
  endpoint?: string;
  token?: string;
  constructor(endpoint?: string | undefined | null, token?: string | undefined | null);
}

/** Result of a `getOrCreate` operation. */
export declare class JsGetOrCreateResult {
  /** Whether the container was newly created (true) or already existed (false). */
  get created(): boolean;
  /** The container handle. */
  get container(): JsContainerHandle;
}

export declare class JsImageHandle {
  pull(image: string): Promise<string>;
  list(): Promise<Array<string>>;
}

export declare class JsVolumeHandle {
  create(name: string): Promise<string>;
  list(): Promise<Array<string>>;
}

export interface JsContainerInfo {
  id: string;
  name?: string;
  state: JsContainerState;
  image: string;
}

export interface JsContainerOptions {
  image: string;
  memoryMib?: number;
  cpus?: number;
  volumes?: Array<string>;
  env?: Array<string>;
  cmd?: Array<string>;
}

export interface JsContainerState {
  status: string;
}

export interface JsOptions {
  homeDir?: string;
}

export interface JsRuntimeMetrics {
  containersCreatedTotal: number;
  numRunningContainers: number;
}
