name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  DEBUG: "napi:*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - target: x86_64-apple-darwin
            flags: "-x"
          - target: aarch64-apple-darwin
            flags: "-x"
          - target: x86_64-pc-windows-msvc
            flags: "-x"
          - target: i686-pc-windows-msvc
            flags: "-x"
          - target: aarch64-pc-windows-msvc
            flags: "-x"
          - target: x86_64-unknown-linux-gnu
            flags: "--use-napi-cross"
          - target: aarch64-unknown-linux-gnu
            flags: "--use-napi-cross"
          - target: x86_64-unknown-linux-musl
            flags: "-x"
          - target: aarch64-unknown-linux-musl
            flags: "-x"
          - target: armv7-unknown-linux-gnueabihf
            flags: "--use-napi-cross"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Run local CI pipeline
        run: npm run ci
