/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: "native" | "wasm32-wasi" | "wasm32-wasip1";

export declare class Certificate {
  constructor();
  static exportChallengeStatic(spkac: string | Buffer, encoding?: string): Buffer;
  static exportPublicKeyStatic(spkac: string | Buffer, encoding?: string): Buffer;
  static verifySpkacStatic(spkac: string | Buffer, encoding?: string): boolean;
  exportChallenge(spkac: string | Buffer, encoding?: string): Buffer;
  exportPublicKey(spkac: string | Buffer, encoding?: string): Buffer;
  verifySpkac(spkac: string | Buffer, encoding?: string): boolean;
}

export declare class Cipheriv {
  constructor(algorithm: string, key: string | Buffer, iv: string | Buffer);
  update(data: string | Buffer, inputEncoding?: string, outputEncoding?: string): string | Buffer;
  setAad(buffer: string | Buffer): void;
  setAutoPadding(autoPadding?: boolean | undefined | null): void;
  final(outputEncoding?: string): string | Buffer;
  getAuthTag(): Buffer;
}

export declare class CryptoKeyPair {
  pubType: string;
  pubAsymType?: string;
  pubBytes: Array<number>;
  privType: string;
  privAsymType?: string;
  privBytes: Array<number>;
  get publicKey(): KeyObject;
  get privateKey(): KeyObject;
}

export declare class Decipheriv {
  constructor(algorithm: string, key: string | Buffer, iv: string | Buffer);
  update(data: string | Buffer, inputEncoding?: string, outputEncoding?: string): string | Buffer;
  setAad(buffer: string | Buffer): void;
  setAuthTag(tag: Buffer): void;
  setAutoPadding(autoPadding?: boolean | undefined | null): void;
  final(outputEncoding?: string): string | Buffer;
}

export declare class DiffieHellman {
  groupOrPrime: string;
  constructor(groupOrPrime: string);
  generateKeys(encoding?: string): string | Buffer;
  getPrime(encoding?: string): string | Buffer;
  getGenerator(encoding?: string): string | Buffer;
  getPublicKey(encoding?: string): string | Buffer;
  getPrivateKey(encoding?: string): string | Buffer;
  setPrivateKey(privateKey: string | Buffer, encoding?: string): void;
  setPublicKey(publicKey: string | Buffer, encoding?: string): void;
  get verifyError(): number;
  computeSecret(
    otherPublicKey: string | Buffer,
    inputEncoding?: string,
    outputEncoding?: string,
  ): string | Buffer;
}

export declare class ECDH {
  curveName: string;
  privateBytes: Array<number>;
  publicBytes: Array<number>;
  constructor(curveName: string);
  static convertKey(key: string | Buffer, curve: string): Buffer;
  generateKeys(encoding?: string, format?: string): string | Buffer;
  getPublicKey(encoding?: string, format?: string): string | Buffer;
  getPrivateKey(encoding?: string): string | Buffer;
  setPrivateKey(privateKey: string | Buffer, encoding?: string): void;
  setPublicKey(publicKey: string | Buffer, encoding?: string): void;
  computeSecret(
    otherPublicKey: string | Buffer,
    inputEncoding?: string,
    outputEncoding?: string,
  ): string | Buffer;
}

export declare class Hash {
  constructor(algorithm: string);
  copy(): Hash;
  update(data: string | Buffer, encoding?: string): void;
  digest(encoding?: string | undefined | null): string | Buffer;
}

export declare class Hmac {
  constructor(algorithm: string, key: string | Buffer);
  update(data: string | Buffer, encoding?: string): void;
  digest(encoding?: string | undefined | null): string | Buffer;
}

export declare class KeyObject {
  keyType: string;
  rawBytes: Array<number>;
  constructor(keyType: string, asymmetricKeyType: string | undefined | null, rawBytes: Buffer);
  get type(): string;
  get asymmetricKeyType(): string | null;
  get symmetricKeySize(): number | null;
  equals(other: KeyObject): boolean;
  export(): Buffer;
}

export declare class Mac {
  constructor(algorithm: string, key: string | Buffer);
  update(data: string | Buffer, encoding?: string): void;
  final(outputEncoding?: string): string | Buffer;
}

export declare class PBKDF2 {
  constructor(digest: string, iterations: number);
  deriveSync(password: string | Buffer, salt: string | Buffer, keylen: number): Buffer;
}

export declare class Pkcs12Result {
  get privateKey(): KeyObject | null;
  get certificate(): X509Certificate | null;
}

export declare class Sign {
  algorithm: string;
  data: Array<number>;
  constructor(algorithm: string);
  update(data: string | Buffer, inputEncoding?: string): void;
  sign(key: string | Buffer, outputEncoding?: string): string | Buffer;
}

export declare class TLS {
  constructor(provider?: string | undefined | null);
  get providerName(): string;
  get isFallback(): boolean;
  getProviderName(): string;
  static getAvailableProviders(): Array<string>;
  getCipherSuites(): Array<string>;
  isCipherSupported(cipher: string): boolean;
}

export declare class Verify {
  algorithm: string;
  data: Array<number>;
  constructor(algorithm: string);
  update(data: string | Buffer, inputEncoding?: string): void;
  verify(key: string | Buffer, signature: string | Buffer): boolean;
}

export declare class X509Certificate {
  constructor(buffer: string | Buffer);
  get ca(): boolean;
  get subject(): string;
  get issuer(): string;
  get validFrom(): string;
  get validTo(): string;
  get fingerprint(): string;
  get fingerprint256(): string;
  get fingerprint512(): string;
  get raw(): Buffer;
  get serialNumber(): string;
  get signatureAlgorithm(): string;
  get signatureAlgorithmOid(): string;
  get publicKey(): KeyObject;
  checkEmail(email: string): boolean;
  checkHost(host: string): boolean;
  checkIp(ip: string): boolean;
  checkIssued(other: X509Certificate): boolean;
  checkPrivateKey(key: KeyObject): boolean;
  verify(publicKey: KeyObject): boolean;
  toJson(): string;
  toString(): string;
}

export declare function argon2(algorithm: string, parameters: Argon2Parameters): Buffer;

export interface Argon2Parameters {
  message: string | Buffer;
  nonce: string | Buffer;
  parallelism: number;
  tagLength: number;
  memory: number;
  passes: number;
  secret?: string | Buffer;
  associatedData?: string | Buffer;
}

export declare function argon2Sync(algorithm: string, parameters: Argon2Parameters): Buffer;

export declare function checkPrime(candidate: string | Buffer): boolean;

export declare function checkPrimeSync(candidate: string | Buffer): boolean;

export declare function createCipheriv(
  algorithm: string,
  key: string | Buffer,
  iv: string | Buffer,
): Cipheriv;

export declare function createDecipheriv(
  algorithm: string,
  key: string | Buffer,
  iv: string | Buffer,
): Decipheriv;

export declare function createDiffieHellman(groupOrPrime: string): DiffieHellman;

export declare function createDiffieHellmanGroup(groupName: string): DiffieHellman;

export declare function createEcdh(curveName: string): ECDH;

export declare function createHash(algorithm: string): Hash;

export declare function createHmac(algorithm: string, key: string | Buffer): Hmac;

export declare function createMac(algorithm: string, key: string | Buffer): Mac;

export declare function createPrivateKey(key: string | Buffer): KeyObject;

export declare function createPublicKey(key: string | Buffer): KeyObject;

export declare function createSecretKey(key: string | Buffer): KeyObject;

export declare function createSign(algorithm: string): Sign;

export declare function createVerify(algorithm: string): Verify;

export declare function decapsulate(key: string | Buffer, ciphertext: string | Buffer): Buffer;

export declare function diffieHellman(
  privateKey: string | Buffer,
  publicKey: string | Buffer,
): Buffer;

export declare function encapsulate(key: string | Buffer): EncapsulateResult;

export interface EncapsulateResult {
  sharedKey: Buffer;
  ciphertext: Buffer;
}

export declare function generateKey(keyType: string, length: number): KeyObject;

export declare function generateKeyPairSync(
  typeName: string,
  modulusLength?: number | undefined | null,
): CryptoKeyPair;

export declare function generateKeySync(keyType: string, length: number): KeyObject;

export declare function generatePrime(size: number): Buffer;

export declare function generatePrimeSync(size: number): Buffer;

export declare function getCipherInfo(nameOrNid: string): string | null;

export declare function getCiphers(): Array<string>;

export declare function getCurves(): Array<string>;

export declare function getDiffieHellman(groupName: string): DiffieHellman;

export declare function getFips(): number;

export declare function getHashes(): Array<string>;

export declare function getMacs(): Array<string>;

export declare function hash(
  algorithm: string,
  data: string | Buffer,
  outputEncoding?: string,
): string | Buffer;

export interface HeapInfo {
  total: number;
  min: number;
  used: number;
  utilization: number;
}

export declare function hkdf(
  digest: string,
  ikm: string | Buffer,
  salt: string | Buffer,
  info: string | Buffer,
  keylen: number,
): Buffer;

export declare function hkdfSync(
  digest: string,
  ikm: string | Buffer,
  salt: string | Buffer,
  info: string | Buffer,
  keylen: number,
): Buffer;

export declare function parsePkcs12(bundle: string | Buffer): Pkcs12Result;

export declare function pbkdf2(
  password: string | Buffer,
  salt: string | Buffer,
  iterations: number,
  keylen: number,
  digest: string,
): Buffer;

export declare function pbkdf2Sync(
  password: string | Buffer,
  salt: string | Buffer,
  iterations: number,
  keylen: number,
  digest: string,
): Buffer;

export declare function privateDecrypt(key: string | Buffer, buffer: string | Buffer): Buffer;

export declare function privateEncrypt(key: string | Buffer, buffer: string | Buffer): Buffer;

export declare function publicDecrypt(key: string | Buffer, buffer: string | Buffer): Buffer;

export declare function publicEncrypt(key: string | Buffer, buffer: string | Buffer): Buffer;

export declare function randomBytes(size: number): Buffer;

export declare function randomFill(buffer: Buffer): Buffer;

export declare function randomFillSync(buffer: Buffer, offset?: number, size?: number): Buffer;

export declare function randomInt(a: number, b?: number | undefined | null): number;

export declare function randomUuid(): string;

export declare function randomUuidV7(): string;

export declare function scrypt(
  password: string | Buffer,
  salt: string | Buffer,
  keylen: number,
): Buffer;

export declare function scryptSync(
  password: string | Buffer,
  salt: string | Buffer,
  keylen: number,
): Buffer;

export declare function secureHeapUsed(): HeapInfo;

export declare function setEngine(engine: string): void;

export declare function setFips(val: boolean): void;

export declare function sign(
  algorithm: string,
  data: string | Buffer,
  key: string | Buffer,
): Buffer;

export declare function timingSafeEqual(a: Buffer, b: Buffer): boolean;

export declare function verify(
  algorithm: string,
  data: string | Buffer,
  key: string | Buffer,
  signature: string | Buffer,
): boolean;
