/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: "native" | "wasm32-wasi" | "wasm32-wasip1";

export declare class Hash {
  constructor(algorithm: string);
  update(data: string | Buffer, encoding?: string | undefined | null): void;
  digest(encoding?: string | undefined | null): string | Buffer;
}

export declare class Hmac {
  constructor(algorithm: string, key: string | Buffer);
  update(data: string | Buffer, encoding?: string | undefined | null): void;
  digest(encoding?: string | undefined | null): string | Buffer;
}

export declare class PBKDF2 {
  constructor(digest: string, iterations: number);
  deriveSync(password: string | Buffer, salt: string | Buffer, keylen: number): Buffer;
}

export declare class TLS {
  constructor(provider?: string | undefined | null);
  get providerName(): string;
  getProviderName(): string;
  static getAvailableProviders(): Array<string>;
  getCipherSuites(): Array<string>;
  isCipherSupported(cipher: string): boolean;
}

export declare function createHash(algorithm: string): Hash;

export declare function createHmac(algorithm: string, key: string | Buffer): Hmac;

export declare function getCiphers(): Array<string>;

export declare function getCurves(): Array<string>;

export declare function getHashes(): Array<string>;

export declare function getMacs(): Array<string>;

export declare function hash(
  algorithm: string,
  data: string | Buffer,
  outputEncoding?: string | undefined | null,
): string | Buffer;

export declare function hkdfSync(
  digest: string,
  ikm: string | Buffer,
  salt: string | Buffer,
  info: string | Buffer,
  keylen: number,
): Buffer;

export declare function pbkdf2Sync(
  password: string | Buffer,
  salt: string | Buffer,
  iterations: number,
  keylen: number,
  digest: string,
): Buffer;

export declare function randomBytes(size: number): Buffer;

export declare function randomFillSync(
  buffer: Buffer,
  offset?: number | undefined | null,
  size?: number | undefined | null,
): Buffer;

export declare function randomUuid(): string;

export declare function timingSafeEqual(a: Buffer, b: Buffer): boolean;
